### ISSUE TITLE
Absolute paths

### ISSUE THREAD

**Issue by mafenet** [1peter10/unwatermarkpdf#2]
I can only use the script with PDF within the same directory

**Comment by 1peter10** [comment]
I tried to fix it with https://github.com/1peter10/unwatermarkpdf/commit/ecc1d94f90218745e9796af2b0c1e9f966a5d933#diff-1fe10bf854ca9c7f5f5387f567171980. Please see if that works for you.

**Comment by mafenet** [comment]
Should be fixed by the pull request, wrong reason for the error
